# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
  - cron: "0 0 *"
  push:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Prepare Git
      run: |
        git config --global user.name "mcc-devel"
        git config --global user.email "jettzheng@foxmail.com"
        git config --global user.author "mcc-devel"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install requests pycountry pyecharts --pre
    - name: Create new Corona.html
      run: |
        python tmain.py
    - name: Push Corona.html to repo
      run: |
        git add Corona.html
        git commit -m "Update Corona.html"
        git push
